# https://taskfile.dev

version: "3"

tasks:
  docker:
    dotenv: ['.env-docker']
    cmds:
      - docker compose -f docker/compose.yaml up --wait --remove-orphans
      - poetry run python scripts/main.py
      - docker compose -f docker/compose.yaml down
  azure:
    dotenv: ['.env-azure']
    cmds:
      - poetry run python scripts/main.py
  default:
    dotenv: ['.env']
    cmds:
      - poetry run python scripts/main.py

