# https://taskfile.dev

version: "3"

tasks:
  default:
    dotenv: ['.env']
    cmds:
      - docker compose -f docker/compose.yaml up --wait --remove-orphans
      - poetry run python scripts/main.py
  down:
    cmds:
      - docker compose -f docker/compose.yaml down
