# https://taskfile.dev

version: "3"

tasks:
  dev:
    dotenv: ['.env-dev']
    cmds:
      - docker compose -f docker/compose.yaml up --wait --remove-orphans
      - poetry run python scripts/main.py
      - docker compose -f docker/compose.yaml down
  az:
    dotenv: ['.env-az']
    cmds:
      - poetry run python scripts/main.py
  default:
    dotenv: ['.env']
    cmds:
      - poetry run python scripts/main.py

