services:
  rdf-delta-server:
    image: ghcr.io/kurrawong/rdf-delta
    ports:
      - 1066:1066
    networks:
      - loadtest
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:1066"]
      retries: 3
      interval: 5s
      timeout: 5s
  rdf-delta-fuseki-server:
    image: ghcr.io/kurrawong/rdf-delta
    command: ["/bin/bash", "-c", "/opt/rdf-delta/fuseki-entrypoint.sh"]
    ports:
      - 3030:3030
    networks:
      - loadtest
    volumes:
      - type: bind
        source: config.ttl
        target: /opt/rdf-delta/config.ttl
    depends_on:
      rdf-delta-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3030/myds"]
      retries: 3
      interval: 5s
      timeout: 5s

networks:
  loadtest:
