services:
  rdf-delta-server:
    image: rdf-delta-server
    ports:
      - "1066:1066"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:1066"]
      retries: 3
      interval: 5s
      timeout: 5s
  rdf-delta-fuseki-server:
    image: rdf-delta-fuseki-server
    ports:
      - "3030:3030"
    volumes:
      - type: bind
        source: config.ttl
        target: /fuseki/config.ttl
    depends_on:
      rdf-delta-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3030/myds" ]
      retries: 3
      interval: 5s
      timeout: 5s
