services:
  rdf-delta-server:
    image: rdf-delta-server
    ports:
      - "1066:1066"
    networks:
        - loadtest
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:1066"]
      retries: 3
      interval: 5s
      timeout: 5s
  rdf-delta-fuseki-server:
    image: rdf-delta-fuseki-server
    ports:
      - "3030:3030"
    networks:
        - loadtest
    volumes:
      - type: bind
        source: config.ttl
        target: /fuseki/config.ttl
    depends_on:
      rdf-delta-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3030/myds"]
      retries: 3
      interval: 5s
      timeout: 5s
  prez:
    image: ghcr.io/rdflib/prez:latest
    ports:
      - 8000:8000
    networks:
        - loadtest
    depends_on:
      rdf-delta-fuseki-server:
        condition: service_healthy
    environment:
      SPARQL_ENDPOINT: http://rdf-delta-fuseki-server:3030/myds/sparql
      ENABLE_SPARQL_ENDPOINT: true
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://prez:8000/health"]
      retries: 3
      interval: 5s
      timeout: 5s

networks:
  loadtest:
